version: "3.1"

services:
  # 单点测试
  # redis:
  #   image: qtrj.i234.me:8084/redis
  #   hostname: redis
  #   ports:
  #     - "7000:6379"
  #   volumes:
  #     - ./redis/data:/data
  #     - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  #   entrypoint: redis-server /usr/local/etc/redis/redis.conf

  # 集群测试
  redis-cluster-allinone:
    # docker run -d -p 7000:7000 -p 7001:7001 -p 7002:7002 -p 7003:7003 -p 7004:7004 -p 7005:7005 -e M1_PORT=7000 -e M2_PORT=7001 -e M3_PORT=7002 -e R1_PORT=7003 -e R2_PORT=7004 -e R3_PORT=7005 shufo/redis-cluster-standalone
    image: qtrj.i234.me:8084/shufo/redis-cluster-standalone
    hostname: redis-cluster
    ports:
      - "7000:7000"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
